<?php

namespace App\Services;

/**
 * Class to generate the token to consume API
 */
class Tokenizer
{

    /**
     * Attributes to be generated by the class
     */
    private $timestamp;
    private $token;

    /**
     * Instanciate tokenizer
     */
    public function __construct()
    {
        $this->timestamp = time();
        $this->token = self::generate($this->timestamp);
    }

    /**
     * Generate token using MD5
     */
    private static function generate(string $timestamp)
    {
        return md5($timestamp . env("APP_KEY"));
    }

    /**
     * Validate incoming token integrity
     */
    public static function isValid(string $token, int $timestamp)
    {
        return (!self::isExpired($token, $timestamp) && self::generate($timestamp) === $token);
    }

    /**
     * Validate incoming token expiration
     */
    public static function isExpired(string $token, int $timestamp)
    {
        return ($timestamp + 86400 < time());
    }

    /**
     * Getters forto retrieve attributes
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    public function getToken()
    {
        return $this->token;
    }
}
