<?php

namespace App\Services;

/**
 * Class to generate the token to consume API
 */
class Tokenizer
{

    /**
     * Attributes to be generated by the class
     */
    private $timestamp;
    private $token;

    /**
     * Instanciate tokenizer
     */
    public function __construct(int $simestamp = null, string $token = null)
    {
        $this->timestamp = $simestamp ?? time();
        $this->token = $token ?? self::generate($this->timestamp);
    }

    /**
     * Generate token using MD5
     */
    private static function generate(int $timestamp)
    {
        return md5($timestamp . env("APP_KEY"));
    }

    /**
     * Validate incoming token integrity
     */
    public function isValid()
    {
        return (!$this->isExpired() && self::generate($this->timestamp) === $this->token);
    }

    /**
     * Validate incoming token expiration
     */
    public function isExpired()
    {
        return ($this->timestamp + 86400 < time());
    }

    /**
     * Getters forto retrieve attributes
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    public function getToken()
    {
        return $this->token;
    }
}
