<?php

namespace App\Services;

/**
 * Class to generate the token to consume API
 */
class Tokenizer
{

    /**
     * Attributes to be generated by the class
     */
    private $timestamp;
    private $token;

    /**
     * Instantiate tokenizer
     *
     * @param int|null $timestamp
     * @param string|null $token
     */
    public function __construct(int $timestamp = null, string $token = null)
    {
        $this->timestamp = $timestamp ?? time();
        $this->token = $token ?? self::generate($this->timestamp);
    }

    /**
     * Generate token using MD5
     *
     * @param int $timestamp
     * @return string
     */
    private static function generate(int $timestamp)
    {
        return md5($timestamp . env("APP_KEY"));
    }

    /**
     * Validate incoming token integrity

     * @return bool
     */
    public function isValid()
    {
        return (!$this->isExpired() && self::generate($this->timestamp) === $this->token);
    }

    /**
     * Validate incoming token expiration

     * @return bool
     */
    public function isExpired()
    {
        return ($this->timestamp + 86400 < time());
    }

    /**
     * Getters to retrieve attributes
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    public function getToken()
    {
        return $this->token;
    }
}
